//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Pulse_MAUI.Resources.Languages {
    using System;
    using System.Reflection;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class UserInterface {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal UserInterface() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Pulse_MAUI.Resources.Languages.UserInterface", typeof(UserInterface).GetTypeInfo().Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Allocated Activity List.
        /// </summary>
        internal static string ActivityListPage_Title {
            get {
                return ResourceManager.GetString("ActivityListPage_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Comments:.
        /// </summary>
        internal static string ActivityPage_Comments {
            get {
                return ResourceManager.GetString("ActivityPage_Comments", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please Enter Text.
        /// </summary>
        internal static string ActivityPage_EditorPlaceHolder {
            get {
                return ResourceManager.GetString("ActivityPage_EditorPlaceHolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Equipment.
        /// </summary>
        internal static string ActivityPage_Equipment {
            get {
                return ResourceManager.GetString("ActivityPage_Equipment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Expected Result:.
        /// </summary>
        internal static string ActivityPage_ExpectedResult {
            get {
                return ResourceManager.GetString("ActivityPage_ExpectedResult", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} Images.
        /// </summary>
        internal static string ActivityPage_Images {
            get {
                return ResourceManager.GetString("ActivityPage_Images", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please Select.
        /// </summary>
        internal static string ActivityPage_PickerPlaceHolder {
            get {
                return ResourceManager.GetString("ActivityPage_PickerPlaceHolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do you want to save the changes?.
        /// </summary>
        internal static string ActivityPage_PromptForSaveMessage {
            get {
                return ResourceManager.GetString("ActivityPage_PromptForSaveMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Abandon Activity.
        /// </summary>
        internal static string ActivityPage_PromptForSaveTitle {
            get {
                return ResourceManager.GetString("ActivityPage_PromptForSaveTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Result:.
        /// </summary>
        internal static string ActivityPage_Result {
            get {
                return ResourceManager.GetString("ActivityPage_Result", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save.
        /// </summary>
        internal static string ActivityPage_Save {
            get {
                return ResourceManager.GetString("ActivityPage_Save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Changes Saved.
        /// </summary>
        internal static string ActivityPage_Saved {
            get {
                return ResourceManager.GetString("ActivityPage_Saved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Status:.
        /// </summary>
        internal static string ActivityPage_Status {
            get {
                return ResourceManager.GetString("ActivityPage_Status", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Step {0} {1}.
        /// </summary>
        internal static string ActivityPage_StepHeader {
            get {
                return ResourceManager.GetString("ActivityPage_StepHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Task Description:.
        /// </summary>
        internal static string ActivityPage_TaskDescription {
            get {
                return ResourceManager.GetString("ActivityPage_TaskDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Activity.
        /// </summary>
        internal static string ActivityPage_Title {
            get {
                return ResourceManager.GetString("ActivityPage_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No.
        /// </summary>
        internal static string ConfirmNo {
            get {
                return ResourceManager.GetString("ConfirmNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yes.
        /// </summary>
        internal static string ConfirmYes {
            get {
                return ResourceManager.GetString("ConfirmYes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to delete this image?.
        /// </summary>
        internal static string DeleteImage_Confirm {
            get {
                return ResourceManager.GetString("DeleteImage_Confirm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} of {1}.
        /// </summary>
        internal static string FileListPage_PageIndicator {
            get {
                return ResourceManager.GetString("FileListPage_PageIndicator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Photo Library.
        /// </summary>
        internal static string FileListPage_PhotoLibrary {
            get {
                return ResourceManager.GetString("FileListPage_PhotoLibrary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Take new Photo.
        /// </summary>
        internal static string FileListPage_TakeNewPhoto {
            get {
                return ResourceManager.GetString("FileListPage_TakeNewPhoto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string FileListPage_Title {
            get {
                return ResourceManager.GetString("FileListPage_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hello {0}.
        /// </summary>
        internal static string MenuPage_HelloTitle {
            get {
                return ResourceManager.GetString("MenuPage_HelloTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Logout.
        /// </summary>
        internal static string MenuPage_Logout {
            get {
                return ResourceManager.GetString("MenuPage_Logout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Synchronise.
        /// </summary>
        internal static string MenuPage_Synchronise {
            get {
                return ResourceManager.GetString("MenuPage_Synchronise", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Synchronising Data.
        /// </summary>
        internal static string MenuPage_Synchronising {
            get {
                return ResourceManager.GetString("MenuPage_Synchronising", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Main Menu.
        /// </summary>
        internal static string MenuPage_Title {
            get {
                return ResourceManager.GetString("MenuPage_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ok.
        /// </summary>
        internal static string Ok_Text {
            get {
                return ResourceManager.GetString("Ok_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to abandon your changes?.
        /// </summary>
        internal static string PromptAbandon {
            get {
                return ResourceManager.GetString("PromptAbandon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Punch List.
        /// </summary>
        internal static string PunchListPage_Title {
            get {
                return ResourceManager.GetString("PunchListPage_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Activity Name:.
        /// </summary>
        internal static string PunchPage_ActivityName {
            get {
                return ResourceManager.GetString("PunchPage_ActivityName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Punch.
        /// </summary>
        internal static string PunchPage_AddPunch {
            get {
                return ResourceManager.GetString("PunchPage_AddPunch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Comments.
        /// </summary>
        internal static string PunchPage_Comments {
            get {
                return ResourceManager.GetString("PunchPage_Comments", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Comm.Sys.:.
        /// </summary>
        internal static string PunchPage_CommSystem {
            get {
                return ResourceManager.GetString("PunchPage_CommSystem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Component Tag:.
        /// </summary>
        internal static string PunchPage_ComponentTag {
            get {
                return ResourceManager.GetString("PunchPage_ComponentTag", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Comp Type:.
        /// </summary>
        internal static string PunchPage_ComponentType {
            get {
                return ResourceManager.GetString("PunchPage_ComponentType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Created By: {0}.
        /// </summary>
        internal static string PunchPage_CreatedBy {
            get {
                return ResourceManager.GetString("PunchPage_CreatedBy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Created Date/Time: {0}.
        /// </summary>
        internal static string PunchPage_CreatedDateTime {
            get {
                return ResourceManager.GetString("PunchPage_CreatedDateTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Discipline Name:.
        /// </summary>
        internal static string PunchPage_DisciplineName {
            get {
                return ResourceManager.GetString("PunchPage_DisciplineName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please Enter Text.
        /// </summary>
        internal static string PunchPage_EditorPlaceHolder {
            get {
                return ResourceManager.GetString("PunchPage_EditorPlaceHolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit Punch.
        /// </summary>
        internal static string PunchPage_EditPunch {
            get {
                return ResourceManager.GetString("PunchPage_EditPunch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ID {0}.
        /// </summary>
        internal static string PunchPage_Id {
            get {
                return ResourceManager.GetString("PunchPage_Id", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 0 Images.
        /// </summary>
        internal static string PunchPage_Images {
            get {
                return ResourceManager.GetString("PunchPage_Images", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to P&amp;ID Ref:.
        /// </summary>
        internal static string PunchPage_PandIdRef {
            get {
                return ResourceManager.GetString("PunchPage_PandIdRef", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please Select.
        /// </summary>
        internal static string PunchPage_PickerPlaceHolder {
            get {
                return ResourceManager.GetString("PunchPage_PickerPlaceHolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Priority.
        /// </summary>
        internal static string PunchPage_PriorityName {
            get {
                return ResourceManager.GetString("PunchPage_PriorityName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Project:.
        /// </summary>
        internal static string PunchPage_Project {
            get {
                return ResourceManager.GetString("PunchPage_Project", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do you want to save the changes?.
        /// </summary>
        internal static string PunchPage_PromptForSaveMessage {
            get {
                return ResourceManager.GetString("PunchPage_PromptForSaveMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Abandon Punch.
        /// </summary>
        internal static string PunchPage_PromptForSaveTitle {
            get {
                return ResourceManager.GetString("PunchPage_PromptForSaveTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Punch Description:.
        /// </summary>
        internal static string PunchPage_PunchDescription {
            get {
                return ResourceManager.GetString("PunchPage_PunchDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Changes Saved.
        /// </summary>
        internal static string PunchPage_Saved {
            get {
                return ResourceManager.GetString("PunchPage_Saved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Status.
        /// </summary>
        internal static string PunchPage_Status {
            get {
                return ResourceManager.GetString("PunchPage_Status", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unit:.
        /// </summary>
        internal static string PunchPage_Unit {
            get {
                return ResourceManager.GetString("PunchPage_Unit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please save changes before adding images.
        /// </summary>
        internal static string SaveWarningMessage {
            get {
                return ResourceManager.GetString("SaveWarningMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Act Name.
        /// </summary>
        internal static string SearchView_ActivityName {
            get {
                return ResourceManager.GetString("SearchView_ActivityName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select All Items.
        /// </summary>
        internal static string SearchView_All {
            get {
                return ResourceManager.GetString("SearchView_All", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Comm Sys.
        /// </summary>
        internal static string SearchView_CommSystemName {
            get {
                return ResourceManager.GetString("SearchView_CommSystemName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tag.
        /// </summary>
        internal static string SearchView_ComponentTag {
            get {
                return ResourceManager.GetString("SearchView_ComponentTag", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Comp Type.
        /// </summary>
        internal static string SearchView_ComponentType {
            get {
                return ResourceManager.GetString("SearchView_ComponentType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Order By.
        /// </summary>
        internal static string SearchView_OrderBy {
            get {
                return ResourceManager.GetString("SearchView_OrderBy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Period.
        /// </summary>
        internal static string SearchView_Period {
            get {
                return ResourceManager.GetString("SearchView_Period", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unit.
        /// </summary>
        internal static string SearchView_UnitName {
            get {
                return ResourceManager.GetString("SearchView_UnitName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last sync date/time was {0}.
        /// </summary>
        internal static string Synchronise_Date {
            get {
                return ResourceManager.GetString("Synchronise_Date", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You must synchronise the application in order to receive data.
        /// </summary>
        internal static string Synchronise_DateNone {
            get {
                return ResourceManager.GetString("Synchronise_DateNone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remember to synchronise for the latest data.
        /// </summary>
        internal static string Synchronise_Reminder {
            get {
                return ResourceManager.GetString("Synchronise_Reminder", resourceCulture);
            }
        }
    }
}
